### ISSUE TITLE
Web Client todo list

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/movie-showtimes#5]
- [x] Hightlight selected item
- [x] Add city select
- [ ] Add owner information
- [x] Fix UTF-8 bug
- [ ] Add detail page for movies / theater
- [x] Implement "Search by theater"
- [ ] Implement "Search by date" (?)
- [ ] Add change city feature

**Comment by HaiNNT** [comment]
Demo comment
